apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zgtqs2jvy-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zgtqs2jvy-dotnet-basic-gitops